---

  # configure hashicorp vault, creating user and start service

- name: Ensure vault user home directory is present
  ansible.builtin.file:
    path: "{{ vault_user_home }}"
    state: directory

- name: Ensure vault user is present
  ansible.builtin.user:
    name: "{{ vault_user }}"
    shell: /bin/false
    home: "{{ vault_user_home }}"
    system: yes

- name: Ensure vault group is present
  ansible.builtin.group:
    name: "{{ vault_group }}"

- name: Ensure vault data directory is present
  ansible.builtin.file:
    path: "{{ vault_raft_path }}"
    state: directory
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0744

- name: Ensure unit file is present and correct
  ansible.builtin.template:
    src: vault_systemd.j2
    dest: /etc/systemd/system/{{ vault_service }}
    mode: 0644
  notify:
    - reload_systemctl

- name: Ensure hashicorp vault config file is present and correct
  ansible.builtin.template:
    src: vault_config.j2
    dest: "{{ vault_config }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_user }}"
  notify:
    - reload_hashicorp_vault

- name: Start vault
  ansible.builtin.service:
    name: "{{ vault_service }}"
    state: started
    enabled: yes