---

# install hashicorp vault via zip download

- name: Get version via URI
  ansible.builtin.uri:
    url: "{{ vault_address }}/v1//sys/health"
    status_code: "{{ vault_valid_return_codes }}"
  register: vault_health
  ignore_errors: true

- name: Set vault installed state
  set_fact:
    vault_installed_version: "{{ vault_health['json']['version'] }}"
  when: vault_health is not failed

- debug:
    msg: "Version found: {{ vault_installed_version }}"
  when: vault_health is not failed

# Should also validate the download
- name: Update or install only when needed based upon vault version
  when: vault_health is failed or vault_installed_version != vault_version
  block:
   - name: Install unzip if it is currently not in an installed state
     ansible.builtin.apt:
       name: unzip
       state: present
       force_apt_get: yes
       update_cache: yes

   - name: Download and extract {{ vault_app }} archive to {{ vault_bin_path }}
     ansible.builtin.unarchive:
       src: "{{ vault_dl_url }}/{{ vault_app }}/{{ vault_version }}/{{ vault_app }}_{{ vault_version }}_{{ vault_osarch }}.zip"
       dest: "{{ vault_bin_path }}"
       remote_src: true
       keep_newer: false
     notify:
        - restart_hashicorp_vault

   - name: remove unzip
     ansible.builtin.apt:
       name: unzip
       state: absent
