---
# Install Hashicorp Vault via repo

- name: add hashicorp signing key
  ansible.builtin.apt_key:
    url: "{{ hashicorp_repo }}/gpg"
    state: present

- name: setup hashicorp repo on Ubuntu
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] {{ hashicorp_repo }} {{ ansible_facts['distribution_release'] }} main"
    state: present

- name: installing vault
  ansible.builtin.package:
    name: "{{ vault_app }}={{ vault_version }}"
    state: present