---

- name: Get health for unseal via URI
  ansible.builtin.uri:
    url: "{{ vault_address }}/v1//sys/health"
    status_code: "{{ vault_valid_return_codes }}"
  register: vault_health
  ignore_errors: false

- name: Set vault initialiation and seal state state
  set_fact:
    vault_initialised: "{{ vault_health['json']['initialized'] | bool }}"
    vault_sealed: "{{ vault_health['json']['sealed'] | bool }}"

- name: Set init node
  debug:
    msg: "{{ hostvars[item]['vault_auto_init'] }}"
  with_items: "{{ groups[vault_server_role_group] }}"
  when:
    - hostvars[item]['vault_auto_init'] is defined

- name: Set init node
  set_fact:
    vault_unseal_keys_b64: "{{ hostvars[item]['vault_unseal_keys_b64'] }}"
  with_items: "{{ groups[vault_server_role_group] }}"
  when:
    - hostvars[item]['vault_auto_init'] is defined
    - hostvars[item]['vault_auto_init'] | bool
    - vault_unseal_keys_b64 is not defined

- name: "Current vault status"
  debug:
    msg: "Vault initialised: {{ vault_initialised }}, vault sealed: {{ vault_sealed }}"

- name: Unseal vault node
  when:
    - vault_initialised
    - vault_sealed
    - vault_auto_unseal
    - vault_unseal_keys_b64 is defined
  block:
    - name: "Current unseal keys"
      debug:
        msg: "Unseal keys to be used:  {{ vault_unseal_keys_b64 }}"

    - name: Useal vault via json post
      ansible.builtin.uri:
        url: "{{ vault_address }}/v1/sys/unseal"
        method: POST
        body_format: json
        body: |
          {
            "key": "{{ item }}"
          }
      loop: "{{ vault_unseal_keys_b64 }}"
      register: vault_unseal_results

- name: Pause for 5 seconds test
  pause:
    seconds: 5

- name: Get health for unseal via URI
  ansible.builtin.uri:
    url: "{{ vault_address }}/v1//sys/health"
    status_code: "{{ vault_valid_return_codes }}"
  register: vault_health
  ignore_errors: false

- name: Set vault initialiation and seal state state
  set_fact:
    vault_initialised: "{{ vault_health['json']['initialized'] | bool }}"
    vault_sealed: "{{ vault_health['json']['sealed'] | bool }}"

- name: "Current vault status"
  debug:
    msg: "Vault initialised: {{ vault_initialised }}, vault sealed: {{ vault_sealed }}"

- name: Unseal member vault node(s)
  when:
    - vault_initialised
    - vault_sealed
    - vault_auto_unseal
    - vault_unseal_keys_b64 is defined
  block:
    - name: "Current unseal keys"
      debug:
        msg: "Unseal keys to be used:  {{ vault_unseal_keys_b64 }}"

    - name: Useal vault via json post
      ansible.builtin.uri:
        url: "{{ vault_address }}/v1/sys/unseal"
        method: POST
        body_format: json
        body: |
          {
            "key": "{{ item }}"
          }
      loop: "{{ vault_unseal_keys_b64 }}"
      register: vault_unseal_results